#!/bin/bash
set -euo pipefail

REPO="KakkoiDev/git-dispatch"
BRANCH="master"
BASE="https://raw.githubusercontent.com/$REPO/$BRANCH"
INSTALL_DIR="$HOME/.git-dispatch"

mkdir -p "$INSTALL_DIR/hooks"

echo "Downloading git-dispatch..."
curl -fsSL "$BASE/git-dispatch.sh" -o "$INSTALL_DIR/git-dispatch.sh"
curl -fsSL "$BASE/hooks/commit-msg" -o "$INSTALL_DIR/hooks/commit-msg"
curl -fsSL "$BASE/hooks/prepare-commit-msg" -o "$INSTALL_DIR/hooks/prepare-commit-msg"
curl -fsSL "$BASE/AGENTS.md" -o "$INSTALL_DIR/AGENTS.md"
curl -fsSL "$BASE/SKILL.md" -o "$INSTALL_DIR/SKILL.md"
chmod +x "$INSTALL_DIR/git-dispatch.sh" "$INSTALL_DIR/hooks/commit-msg" "$INSTALL_DIR/hooks/prepare-commit-msg"

git config --global alias.dispatch "!bash $INSTALL_DIR/git-dispatch.sh"
echo "Installed: git dispatch → $INSTALL_DIR/git-dispatch.sh"
echo ""
echo "What this installer did:"
echo "  - Added global git alias: git dispatch"
echo "  - Downloaded: git-dispatch.sh, hooks, AGENTS.md, SKILL.md"
echo ""
echo "What this installer did NOT do:"
echo "  - Did not install/update AI agent or skill files"
echo ""
echo "Usage:"
echo "  git dispatch init [--base <branch>] [--target-pattern <pattern>] [--mode <independent|stacked>]"
echo "  git dispatch apply [--dry-run]"
echo "  git dispatch cherry-pick --from <source|id> --to <source|id>"
echo "  git dispatch push --from <id|all|source> [--dry-run]"
echo "  git dispatch status"
echo "  git dispatch reset [--force]"
echo "  git dispatch help"
echo ""
echo "Optional AI setup:"
echo "  Claude (skills + agent):"
echo "    mkdir -p ~/.claude/skills/git-dispatch ~/.claude/agents"
echo "    cp \"$INSTALL_DIR/SKILL.md\" ~/.claude/skills/git-dispatch/SKILL.md"
echo "    cp \"$INSTALL_DIR/AGENTS.md\" ~/.claude/agents/git-dispatch.md"
echo ""
echo "  Codex (skills + repo agent file):"
echo "    mkdir -p \"\${CODEX_HOME:-$HOME/.codex}/skills/git-dispatch\""
echo "    cp \"$INSTALL_DIR/SKILL.md\" \"\${CODEX_HOME:-$HOME/.codex}/skills/git-dispatch/SKILL.md\""
echo "    cp \"$INSTALL_DIR/AGENTS.md\" /path/to/your/project/AGENTS.md"
echo ""
echo "  Gemini (repo instructions):"
echo "    cp \"$INSTALL_DIR/AGENTS.md\" /path/to/your/project/AGENTS.md"
echo "    cp \"$INSTALL_DIR/SKILL.md\" /path/to/your/project/GEMINI.md"
